version: '3'
services:
  cms:
    build:
        context: .
        dockerfile: ./Dockerfile
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    env_file:
      - ./app/.env
    volumes:
      - ./app:/srv/app
      - /srv/app/node_modules
      - /srv/app/dist
      - /srv/app/.cache
    depends_on:
      - db
    command: yarn develop
    networks:
      - app-network

  db:
    container_name: mysql
    image: mysql:8.0.32
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:1.25.3
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cms
    restart: always
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
